NetBios: fixes #434, added two functions to common.
dsccommunity/NetworkingDsc pull request #479
Opened 2020-10-27 20:37 UTC by phbits

#### Pull Request (PR) description
Restructured GET and SET functions based on the following:

- An adapter can only be configured via WMI method if IPEnabled=$true. Otherwise the registry key must be configured. This satisfies disabled and disconnected states.
- Current setting can only be obtained via the registry since WMI is unreliable due to various adapter states.
- Only configure an adapter when not in the desired state.
- Retain wildcard support.

#### This Pull Request (PR) fixes the following issues

    - Fixes #434

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2020-11-07 06:29 UTC, PlagueHO commented
Hi @phbits - thanks for submitting this - there are a few style issues causing the HQRM failures. I can identify them for you if you like? Sorry for taking a long time to get onto these - I'm completely snowed under with day job till Dec. But I'll be back across all this then.

2020-12-01 07:39 UTC, PlagueHO commented
Hi @phbits - I'm back on board now and have some capacity to work on DSC again. Are you planning to work on this? There are a few style and other issues that are causing this to fail - do you want me to do the review and identify key issues?

2020-12-02 19:50 UTC, phbits commented
Hi @PlagueHO! I'm happy to continue working on this. The HQRM errors about a new line after an opening brace weren't making any sense to me so I put it on hold to learn Pester as the Unit tests will need to be fixed due to this PR. Let me take another look at the HQRM requirements and I'll update this thread.

2020-12-06 05:44 UTC, PlagueHO requested changes
Hi @phbits - recommend using VSCode as your editor and enable the PS extension. This will automatically highlight many HQRM violations with underlines. Much easier that trying to pick them up other ways. I've identified some for you here.

Recommend reviewing style guidelines here: https://dsccommunity.org/styleguidelines/

> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-:-MNqXWdgE6_gB8wUaCuP:b1vs6cc)* status: 1 of 3 files reviewed, 23 unresolved discussions (waiting on @phbits and @PlagueHO)

___
*[CHANGELOG.md, line 13 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqWbB-9-LB3WXCOzJq:-MNqWbB-9-LB3WXCOzJr:bnnvygo) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/CHANGELOG.md#L13)):*
> ```Markdown
> 
> - NetBios
>   - Fixes [Issue #434](https://github.com/dsccommunity/NetworkingDsc/issues/434).
> ```

Can you describe the fix?
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 86 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqWeOl9_Cm-U3mbVB-:-MNqWeOl9_Cm-U3mbVB0:bnwuqvb) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L86)):*
> ```PowerShell
>         resource is not in the desired state.
>     #>
>     if ( $netAdapter -is [Array] )
> ```

HQRM:
```powershell
if ($netAdapter -is [System.Array])
```
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 88 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqWk0Y--2tMGn_AOZh:-MNqWk0Y--2tMGn_AOZi:b1oxid0) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L88)):*
> ```PowerShell
>     if ( $netAdapter -is [Array] )
>     {
>         [string[]] $SettingResults = @()
> ```

Can you use ```[System.String[]]```?
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 90 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqWqwT5r3AXP4Z3192:-MNqWqwT5r3AXP4Z3193:b-utcbnx) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L90)):*
> ```PowerShell
>         [string[]] $SettingResults = @()
> 
>         foreach ( $netAdapterItem in $netAdapter )
> ```

HQRM:
```powershell
foreach ($netAdapterItem in $netAdapter)
```
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 94 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqXC3B3OpmkmFhcGLF:-MNqXC3B3OpmkmFhcGLG:b7kj05f) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L94)):*
> ```PowerShell
>             $SettingResults += Get-NetAdapterNetbiosOptionsFromRegistry -NetworkAdapterGUID $netAdapterItem.GUID -Setting $Setting
> 
>             Write-Verbose -Message ($script:localizedData.CurrentNetBiosSettingMessage -f $netAdapterItem.NetConnectionID,$SettingResults[-1])
> ```

Can you add space before comma
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 97 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqXF5H2tccwwqGMvZX:-MNqXF5H2tccwwqGMvZY:b-yh9h9n) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L97)):*
> ```PowerShell
>         }
> 
>         [string[]] $WrongSettings = $SettingResults | Where-Object{ $_ -ne $Setting }
> ```

HQRM:
```powershell
$wrongSettings = $SettingResults | Where-Object -FilterScript {
    $_ -ne $Setting
}
```
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 99 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqXpZV30LdirirElDF:-MNqXpZV30LdirirElDG:b-f5zzuu) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L99)):*
> ```PowerShell
>         [string[]] $WrongSettings = $SettingResults | Where-Object{ $_ -ne $Setting }
> 
>         if ([System.String]::IsNullOrEmpty($WrongSettings) -eq $false)
> ```

Can use:
```powershell
if (-not [System.String]::IsNullOrEmpty($wrongSettings))
```

Should also be lowercase variable name.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 101 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqXui8Clu1O1FvnnW2:-MNqXui8Clu1O1FvnnW3:b-blhpm) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L101)):*
> ```PowerShell
>         if ([System.String]::IsNullOrEmpty($WrongSettings) -eq $false)
>         {
>             [string] $Setting = $WrongSettings[0]
> ```

No need to specify type.
Should be lower case variable name.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 161 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqYD9d7LFffspJGkuF:-MNqYD9d7LFffspJGkuG:b-yo07ol) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L161)):*
> ```PowerShell
>     }
> 
>     if ( $netAdapter -is [Array] )
> ```

HQRM style issues. Don't use type accelerators.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 163 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqYI156pmqTUJOz1fC:-MNqYI156pmqTUJOz1fD:boslc6m) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L163)):*
> ```PowerShell
>     if ( $netAdapter -is [Array] )
>     {
>         foreach ( $netAdapterItem in $netAdapter )
> ```

HQRM style issues.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 165 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqYJ159s5MUdik9gDh:-MNqYJ159s5MUdik9gDi:b-qklq1y) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L165)):*
> ```PowerShell
>         foreach ( $netAdapterItem in $netAdapter )
>         {
>             $CurrentValue = Get-NetAdapterNetbiosOptionsFromRegistry -NetworkAdapterGUID $netAdapterItem.GUID -Setting $Setting
> ```

Variable name should start with lower case.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 168 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqYIbAC1PWQD5BnTt4:-MNqYIbAC1PWQD5BnTt5:boslc6m) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L168)):*
> ```PowerShell
> 
>             # Only make changes if necessary
>             if ( $CurrentValue -ne $Setting )
> ```

HQRM style issues.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 232 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqZU3-1dhqHB3zPEYV:-MNqZU3-1dhqHB3zPEYW:b-t9zhx1) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L232)):*
> ```PowerShell
> <#
> .SYNOPSIS
>     Returns the NetbiosOptions value for a network adapter.
> ```

Blank line after this one.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 236 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqZWaNCYjsiNcqmaGf:-MNqZWaNCYjsiNcqmaGg:b-t9zhx1) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L236)):*
> ```PowerShell
>     Most reliable method of getting this value since network adapters
>     can be in any number of state [...]

2020-12-09 15:26 UTC, phbits commented
@PlagueHO - Thanks for the thorough review and feedback! I finished the unit tests yesterday and all the tests are completing successfully. Will start working on your suggested HQRM edits.

2020-12-09 18:25 UTC, phbits reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/479)* status: 0 of 4 files reviewed, 23 unresolved discussions (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 13 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqWbB-9-LB3WXCOzJq:-MO7g9wk3sm6TCx8vBZy:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/CHANGELOG.md#L13)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you describe the fix?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 86 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqWeOl9_Cm-U3mbVB-:-MO7gKlI0lBMt3hci0I1:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L86)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

HQRM:
```powershell
if ($netAdapter -is [System.Array])
```
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 88 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqWk0Y--2tMGn_AOZh:-MO7gNp34DskVopS2NkK:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L88)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use ```[System.String[]]```?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 90 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqWqwT5r3AXP4Z3192:-MO7gPDj8usoYmrwYYGD:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L90)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

HQRM:
```powershell
foreach ($netAdapterItem in $netAdapter)
```
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 94 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqXC3B3OpmkmFhcGLF:-MO7gSMY-GLPAPPjsByp:b-qmjvg3) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L94)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add space before comma
</blockquote></details>

Figured you meant a space after comma.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 97 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqXF5H2tccwwqGMvZX:-MO7gc--8i5Ogp80RI59:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L97)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

HQRM:
```powershell
$wrongSettings = $SettingResults | Where-Object -FilterScript {
    $_ -ne $Setting
}
```
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 99 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqXpZV30LdirirElDF:-MO7gfsY6TOXBqQ9Pu0_:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L99)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can use:
```powershell
if (-not [System.String]::IsNullOrEmpty($wrongSettings))
```

Should also be lowercase variable name.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 101 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqXui8Clu1O1FvnnW2:-MO7gjZqCeB29Q8cJcmr:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L101)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

No need to specify type.
Should be lower case variable name.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 161 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqYD9d7LFffspJGkuF:-MO7glIE0-aaT6X_kFgz:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L161)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

HQRM style issues. Don't use type accelerators.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 163 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqYI156pmqTUJOz1fC:-MO7gmbW76Sd2MI1eaN1:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L163)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

HQRM style issues.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 165 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqYJ159s5MUdik9gDh:-MO7goW-9fpwWvWcSJZ5:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L165)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Variable name should start with lower case.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 168 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqYIbAC1PWQD5BnTt4:-MO7gpiF1BvFQwBf6lu4:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L168)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

HQRM style issues.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 232 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqZU3-1dhqHB3zPEYV:-MO7grnO3iOyr8wJ0DTA:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L232)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Blank line after this one.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 236 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqZWaNCYjsiNcqmaGf:-MO7gsNp6eRrBaK_Yp68:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L236)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Blank line after this one.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 238 at r2](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MNqZXM18SclvZPD7Bu2:-MO7gtu8-dpcEKOQxLmJ:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/129a9cf95a2b206621225fac4649f06cd18beafd/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L238)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Blank line after this one.
</blockquote> [...]

2020-12-10 04:01 UTC, phbits commented
@PlagueHO - All the tests are completing successful for this PR so I'm going to work on the DnsServerAddress PR.

2020-12-12 04:26 UTC, PlagueHO requested changes
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/479)* status: all files reviewed, 17 unresolved discussions (waiting on @phbits)

___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 97 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOKBFS2-5qm6spSF78n:-MOKBFS2-5qm6spSF78o:b-r9z02) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L97)):*
> ```PowerShell
>         }
> 
>         [System.String[]] $wrongSettings = $settingResults | Where-Object -FilterScript {
> ```

Looking at this, I don't think you need to define the type here either because it is implicit given that $settingResults is already a [System.String[]].
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 233 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7Cir4C2luARP407B:-MOK7Cir4C2luARP407C:bwygm1y) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L233)):*
> ```PowerShell
> 
> <#
> .SYNOPSIS
> ```

Sorry, I missed this one - minor nitpick: can you indent all lines in this block to match previous comment blocks? 
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 270 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOKAXA70qfBMSKgZoAn:-MOKAXA70qfBMSKgZoAo:bg6izcb) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L270)):*
> ```PowerShell
> 
>     $registryNetbiosOptions = Get-ItemPropertyValue -Name 'NetbiosOptions' `
>                     -Path "HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces\Tcpip_$($NetworkAdapterGUID)"
> ```

Can we add this path as a constant to the top of the module? E.g.
```powershell
$hklmInterfacesPath = 'HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces\'
```
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 285 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7q9dAcVAbNQfiyai:-MOK7q9dAcVAbNQfiyaj:b2t2ed7) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L285)):*
> ```PowerShell
>             return 'Default'
>         }
>         1
> ```

Can add blank line above this one.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 289 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7szrAFU3lkQDvKg3:-MOK7szrAFU3lkQDvKg4:b2t2ed7) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L289)):*
> ```PowerShell
>             return 'Enable'
>         }
>         2
> ```

Can add blank line above this one.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 296 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7Y6aBZlDCPy8RSnB:-MOK7Y6aBZlDCPy8RSnC:bigb5po) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L296)):*
> ```PowerShell
>         {
>             # Unknown value. Returning invalid setting to trigger Set-TargetResource
>             [string[]] $invalidSetting = 'Default','Enable','Disable' | Where-Object -FilterScript {
> ```

You can remove the type assignment as it is already implicitly a `[System.String[]]`.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 306 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7fcXBAkjgWLj5JbT:-MOK7fcXBAkjgWLj5JbU:b-2yunw0) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L306)):*
> ```PowerShell
> 
> <#
> .SYNOPSIS
> ```

Can you indent all lines in comment block?
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 333 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK94uRDgA5gfwhYwhT:-MOK94uS6mBojZMH51Fc:b-xky72o) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L333)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [System.Object]
>         $NetworkAdapterObj,
> ```

Nitpick: Could this parameter name not include `Obj`? Alternatively expand `Obj` to `Object`.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 345 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK9VvF26e3RMmis5uf:-MOK9VvF26e3RMmis5ug:b-nmx0kt) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L345)):*
> ```PowerShell
>     )
> 
>     Write-Verbose -Message ($script:localizedData.SetNetBiosMessage -f $InterfaceAlias,$Setting)
> ```

Can you add space after comma? Suggest using VSCode autoformatting - it will fix all these kinds of minor style issues: https://dscottraynsford.wordpress.com/2017/11/18/auto-formatting-powershell-in-visual-studio-code/
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 367 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7koJ5j8Dg63TMbqf:-MOK7koJ5j8Dg63TMbqg:b-q1vpw4) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L367)):*
> ```PowerShell
>     {
>         <#
>         IPEnabled=$false can only be configured via registry
> ```

Can you indent this line and the next?
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 371 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOKAsSV0uemHAjVlFxb:-MOKAsSV0uemHAjVlFxc:b-wlq5f2) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L371)):*
> ```PowerShell
>         #>
>         $setItemPropertyParameters = @{
>             Path  = "HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces\Tcpip_$($NetworkAdapterObj.SettingID)"
> ```

This could then use the constant defined earlier.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 377 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7n7J64TMBEviqVS-:-MOK7n7J64TMBEviqVS0:b-8kes5p) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L377)):*
> ```PowerShell
>         $null = Set-ItemProperty @setItemPropertyParameters
>     }
> ```

Can remove this blank line.
___
*[tests/Unit/DSC_NetBios.Tests.ps1, line 190 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK8AGfDwlvG44du41-:-MOK8AGfDwlvG44du410:b-y0e4xp) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/tests/Unit/DSC_NetBios.Tests.ps1#L190)):*
> ```PowerShell
>                         Mock -CommandName Get-CimInstance -MockWith $script:mockNetadapterA
>                         Mock -CommandName Get-ItemPropertyValue -MockWith { return $testCase.SettingInt } `
>                                                                 -ParameterFilter $script:getItemPropertyValue_NetbiosOptions_One_ParameterFilter
> ```

Can you reduce indent on this line to prevent wrap?
___
*[tests/Unit/DSC_NetBios.Tests.ps1, line 191 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK8-Lr0ZfF3jUDwwUS:-MOK8-Lr0ZfF3jUDwwUT:b1onxf5) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/tests/Unit/DSC_NetBios.Tests.ps1#L191)):* [...]

2020-12-12 04:50 UTC, PlagueHO requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/479)* status: all files reviewed, 18 unresolved discussions (waiting on @phbits)

___
*[CHANGELOG.md, line 13 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOKH4vTC-2Mxz2FeAhc:-MOKH4vTC-2Mxz2FeAhd:b-evit7b) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/CHANGELOG.md#L13)):*
> ```Markdown
> 
> - NetBios
>   - Fixes configuring network adapters in a disconnected or disabled state. Fixes [Issue #434](https://github.com/dsccommunity/NetworkingDsc/issues/434).
> ```

Just for consistency can you use the format ` - Fixes configuring network adapters in a disconnected or disabled state - fixes [Issue #434](https://github.com/dsccommunity/NetworkingDsc/issues/434).`


<!-- Sent from Reviewable.io -->

2020-12-15 03:52 UTC, phbits reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/479)* status: 1 of 4 files reviewed, 18 unresolved discussions (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 13 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOKH4vTC-2Mxz2FeAhc:-MOZJ21t-Yuxduk4_a9q:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/CHANGELOG.md#L13)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Just for consistency can you use the format ` - Fixes configuring network adapters in a disconnected or disabled state - fixes [Issue #434](https://github.com/dsccommunity/NetworkingDsc/issues/434).`
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 97 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOKBFS2-5qm6spSF78n:-MON218-Ejwy8qMK4GYj:baetbrk) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L97)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Looking at this, I don't think you need to define the type here either because it is implicit given that $settingResults is already a [System.String[]].
</blockquote></details>

It defaults to System.Object[] if not explicitly declared. Some time ago this one got the best of me and took far longer then I'd like to admit to finally identify.

```powershell
PS C:\> [System.String[]] $settingResults = 'Enable','Disable','Default'
PS C:\> $wrongSettings = $settingResults | Where-Object -FilterScript { $_ -ne 'Enable' }
PS C:\> Get-Member -InputObject $wrongSettings | findstr 'TypeName'
   TypeName: System.Object[]
PS C:\> [System.String[]] $wrongSettings = $settingResults | Where-Object -FilterScript { $_ -ne 'Enable' }
PS C:\> Get-Member -InputObject $wrongSettings | findstr 'TypeName'
   TypeName: System.String[]
```
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 233 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7Cir4C2luARP407B:-MOZOuwFBawZW-TkGfUU:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L233)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Sorry, I missed this one - minor nitpick: can you indent all lines in this block to match previous comment blocks? 
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 270 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOKAXA70qfBMSKgZoAn:-MOZJohWCDMj6Sr8WEC1:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L270)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we add this path as a constant to the top of the module? E.g.
```powershell
$hklmInterfacesPath = 'HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces\'
```
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 285 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7q9dAcVAbNQfiyai:-MOZJpzQ52w1nVPRWZXb:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L285)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can add blank line above this one.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 289 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7szrAFU3lkQDvKg3:-MOZJqhUBAeElWFuuMWz:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L289)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can add blank line above this one.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 296 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7Y6aBZlDCPy8RSnB:-MON6Zqy2jcnOaGbuu9s:b1vkhil) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L296)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

You can remove the type assignment as it is already implicitly a `[System.String[]]`.
</blockquote></details>

Doh! Missed setting this to [System.String[]]. Leaving the explicit assignment as mentioned above.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 306 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7fcXBAkjgWLj5JbT:-MOZJvOAEzY3CY0ica7S:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L306)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you indent all lines in comment block?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 333 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK94uRDgA5gfwhYwhT:-MOZJwuN3M2lYk3z_gxT:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L333)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: Could this parameter name not include `Obj`? Alternatively expand `Obj` to `Object`.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 345 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK9VvF26e3RMmis5uf:-MOZJyv24074NnLIc83T:b-qyek5t) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L345)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add space after comma? Suggest using VSCode autoformatting - it will fix all these kinds of minor style issues: https://dscottraynsford.wordpress.com/2017/11/18/auto-formatting-powershell-in-visual-studio-code/
</blockquote></details>

Done. Thanks for the reference. Much appreciated!
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 367 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7koJ5j8Dg63TMbqf:-MOZK0w414x7Z3JPiG1J:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L367)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you indent this line and the next?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 371 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOKAsSV0uemHAjVlFxb:-MOZK25yAHDovzt8cWIP:b-896fix) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/ec48dafb4c5fd4816e0c80aca37fd99aeb61462a/source/DSCResources/DSC_NetBios/DSC_NetBios.psm1#L371)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This could then use the constant defined earlier.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_NetBios/DSC_NetBios.psm1, line 377 at r4](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MOK7n7J64 [...]

2020-12-26 08:22 UTC, PlagueHO commented
Hi @phbits - can you resolve the conflicts on this one? Check that the changes in the CHANGELOG.md appear in the [Unreleased] section.

2020-12-27 03:29 UTC, phbits reviewed
Updated CHANGELOG.md.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-:-MPXEKnC1IYXbZ7md3aD:bi6ser)* status: 1 of 4 files reviewed, 18 unresolved discussions (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2020-12-30 05:47 UTC, PlagueHO commented
Hi @phbits - looks like there are still conflicts in the CHANGELOG.md

2020-12-30 16:39 UTC, phbits commented
@PlagueHO , I resolved the CHANGELOG conflict. Will resolve the DnsServerAddress PR after this PR is closed.

2020-12-31 20:56 UTC, PlagueHO requested changes
> Reviewed 2 of 3 files at r5, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/479)* status: all files reviewed, 1 unresolved discussion (waiting on @phbits)

___
*[tests/Unit/DSC_NetBios.Tests.ps1, line 858 at r7](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MPu_5c_1LbxcSM-sm0N:-MPu_5c_1LbxcSM-sm0O:b-wcnmob) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/36ccfee0614060bb728fedc29e69b8ae0d9fb8c3/tests/Unit/DSC_NetBios.Tests.ps1#L858)):*
> ```PowerShell
>             }
>         }
>         Describe 'DSC_NetBios\Get-NetAdapterNetbiosOptionsFromRegistry' {
> ```

Some final style nitpicks (sorry :grin: - I know these are a bit of a pain) - can you a blank line before each `Describe` and `Context` block?


<!-- Sent from Reviewable.io -->

2021-01-01 01:17 UTC, phbits reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/479)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[tests/Unit/DSC_NetBios.Tests.ps1, line 858 at r7](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-MPu_5c_1LbxcSM-sm0N:-MPvVVOL5V9S3svsPy52:bdtndq4) ([raw file](https://github.com/dsccommunity/networkingdsc/blob/36ccfee0614060bb728fedc29e69b8ae0d9fb8c3/tests/Unit/DSC_NetBios.Tests.ps1#L858)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Some final style nitpicks (sorry :grin: - I know these are a bit of a pain) - can you a blank line before each `Describe` and `Context` block?
</blockquote></details>

NP, blank lines added. Happy New Year! :tada:


<!-- Sent from Reviewable.io -->

2021-02-22 04:57 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

I am sorry for how long this took.

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/networkingdsc/479#-:-MU758Nu33ZFrtEepwBo:b-1frku5)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-22 04:57 UTC, merged