Migrate to Pester 5
dsccommunity/NetworkingDsc pull request #532
Opened 2024-11-24 16:04 UTC by dan-hughes

#### Pull Request (PR) description

Migrate all tests to Pester 5

#### This Pull Request (PR) fixes the following issues

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2024-11-24 16:25 UTC, johlju requested changes
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-hughes)

___
*[`source/Private/Convert-CIDRToSubnetMask.ps1` line 9 at r1](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OCTyD2F9yQITIW393ZG:-OCTyD2F9yQITIW393ZH:bwggnrj) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/1ccfa393f291c5d53fd6e35065849ce4beca0a15/source/Private/Convert-CIDRToSubnetMask.ps1#L9)):*
> ```PowerShell
>         The array of addresses to that need to be converted.
> #>
> function Convert-CIDRToSubnetMask
> ```

If these are gonna be used in the MOF resources they need to be public functions, not private. Throughout where function is needed in MOF resource.



_Code quote:_
```PowerShell
Convert-CIDRToSubnetMask
```
___
*[`tests/TestHelpers/CommonTestHelper.psm1` line 210 at r1](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OCTz-k19XQg5vT9hPVN:-OCTz-k19XQg5vT9hPVO:b-xfswe0) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/d68f7af2e06c01fe1e3c64e6455d7e07df3f1970/tests/TestHelpers/CommonTestHelper.psm1#L210)):*
> ```PowerShell
>     Test-NetworkTeamIntegrationEnvironment, `
>     New-IntegrationLoopbackAdapter, `
>     Remove-IntegrationLoopbackAdapter
> ```

Maybe here we should keep the export-modulemember since it says what to export even if there are more (private) functions in the module. :thinking: 



_Code quote:_
```PowerShell
Export-ModuleMember -Function `
    Get-InvalidArgumentRecord, `
    Get-InvalidOperationRecord, `
    Test-NetworkTeamIntegrationEnvironment, `
    New-IntegrationLoopbackAdapter, `
    Remove-IntegrationLoopbackAdapter
```


<!-- Sent from Reviewable.io -->

2024-11-24 16:37 UTC, dan-hughes commented
> > Reviewed 29 of 29 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532)_ status: all files reviewed, 2 unresolved discussions (waiting on @dan-hughes)
> 
> _[`source/Private/Convert-CIDRToSubnetMask.ps1` line 9 at r1](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OCTyD2F9yQITIW393ZG:-OCTyD2F9yQITIW393ZH:bwggnrj) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/1ccfa393f291c5d53fd6e35065849ce4beca0a15/source/Private/Convert-CIDRToSubnetMask.ps1#L9)):_
> 
> > ```powershell
> >         The array of addresses to that need to be converted.
> > #>
> > function Convert-CIDRToSubnetMask
> > ```
> 
> If these are gonna be used in the MOF resources they need to be public functions, not private. Throughout where function is needed in MOF resource.
> 
> _Code quote:_
> 
> ```powershell
> Convert-CIDRToSubnetMask
> ```
> 
> _[`tests/TestHelpers/CommonTestHelper.psm1` line 210 at r1](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OCTz-k19XQg5vT9hPVN:-OCTz-k19XQg5vT9hPVO:b-xfswe0) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/d68f7af2e06c01fe1e3c64e6455d7e07df3f1970/tests/TestHelpers/CommonTestHelper.psm1#L210)):_
> 
> > ```powershell
> >     Test-NetworkTeamIntegrationEnvironment, `
> >     New-IntegrationLoopbackAdapter, `
> >     Remove-IntegrationLoopbackAdapter
> > ```
> 
> Maybe here we should keep the export-modulemember since it says what to export even if there are more (private) functions in the module. 🤔
> 
> _Code quote:_
> 
> ```powershell
> Export-ModuleMember -Function `
>     Get-InvalidArgumentRecord, `
>     Get-InvalidOperationRecord, `
>     Test-NetworkTeamIntegrationEnvironment, `
>     New-IntegrationLoopbackAdapter, `
>     Remove-IntegrationLoopbackAdapter
> ```

Yeah, give me a minute. I wanted to check the build worked. I'm going to get all the integration tests up and running as there are HQRM fixes required 😊

2024-11-24 17:36 UTC, johlju commented
No worries No hurry. I saw it was not draft so when I had a minute left I just browsed through it. 🙂

2025-01-04 09:53 UTC, dan-hughes commented
@johlju, do you have time to starting looking through this? 

I have just the firewall and firewallprofile to finish off.

2025-01-04 10:45 UTC, johlju commented
I have seen this but as it was still draft I didn’t do anything, but can look into that as well, probably after the ”WSMan” PR.

2025-01-04 13:31 UTC, dan-hughes commented
I didn't want to mark it as ready until I finished. The last tests were not Pester 5 friendly.

2025-01-05 13:27 UTC, dan-hughes commented
@johlju, ready to go.

2025-01-12 10:25 UTC, johlju requested changes
> Reviewed 24 of 45 files at r3, 55 of 66 files at r4, 4 of 4 files at r5, 1 of 2 files at r6, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-hughes)

___
*[`tests/TestHelpers/CommonTestHelper.psm1` line 210 at r1](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OCTz-k19XQg5vT9hPVN:-OGOyzLC2kHajVD1FVqZ:b-11e10w) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/d68f7af2e06c01fe1e3c64e6455d7e07df3f1970/tests/TestHelpers/CommonTestHelper.psm1#L210)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Yeah, give me a minute. I wanted to check the build worked. I'm going to get all the integration tests up and running as there are HQRM fixes required 😊
</blockquote></details>

Should we uncomment the Export-ModuleMember block now?
___
*[`tests/Integration/DSC_NetAdapterName.Integration.Tests.ps1` line 198 at r7](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OGOy3Wo2mBmA9RMs7p_:-OGOy3Wo2mBmA9RMs7pa:b-4hgkek) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/977ecead86841ad30946fcc25c16d2d32aacb499/tests/Integration/DSC_NetAdapterName.Integration.Tests.ps1#L198)):*
> ```PowerShell
>                 $_.ConfigurationName -eq "$($script:dscResourceName)_Config_NameOnly"
>             }
>             
> ```

Looks like there are blank spaces on this line, don't we have a VS Code project setting for automatically trimming white space at end of line on save? :thinking:  



_Code quote:_
```PowerShell
···········
```
___
*[`source/Public/Get-DnsClientServerStaticAddress.ps1` line 16 at r7](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OGOvorl9Cf0xRNpmbCm:-OGOvorl9Cf0xRNpmbCn:bsshy4o) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/977ecead86841ad30946fcc25c16d2d32aacb499/source/Public/Get-DnsClientServerStaticAddress.ps1#L16)):*
> ```PowerShell
>         IP address family.
> #>
> function Get-DnsClientServerStaticAddress
> ```

I wonder if we should prefix each public function (commented on another module as well). If there is another exported command with the same name it will be a conflict, so wonder if we should prefix all commands with `NetDsc` or something to make sure they are unique? 

What do you think?



_Code quote:_
```PowerShell
Get-DnsClientServerStaticAddress
```


<!-- Sent from Reviewable.io -->

2025-01-12 13:31 UTC, dan-hughes reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532)* status: 95 of 105 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[`tests/Integration/DSC_NetAdapterName.Integration.Tests.ps1` line 198 at r7](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OGOy3Wo2mBmA9RMs7p_:-OGPhRYQCLtToDhZYpSR:b-tcho59) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/977ecead86841ad30946fcc25c16d2d32aacb499/tests/Integration/DSC_NetAdapterName.Integration.Tests.ps1#L198)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Looks like there are blank spaces on this line, don't we have a VS Code project setting for automatically trimming white space at end of line on save? :thinking:
</blockquote></details>

Fixed, not sure why vscode/PSSA was not picking this up. Checked all the integration test files.
___
*[`source/Public/Get-DnsClientServerStaticAddress.ps1` line 16 at r7](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OGOvorl9Cf0xRNpmbCm:-OGPh6oB36Ye_r6vvnlB:bh0f5hf) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/977ecead86841ad30946fcc25c16d2d32aacb499/source/Public/Get-DnsClientServerStaticAddress.ps1#L16)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I wonder if we should prefix each public function (commented on another module as well). If there is another exported command with the same name it will be a conflict, so wonder if we should prefix all commands with `NetDsc` or something to make sure they are unique? 

What do you think?
</blockquote></details>

Valid point, but instead of a prefix maybe a suffix instead? Then searching for usages across repos may be easier as atleast the start of the function name matches.


<!-- Sent from Reviewable.io -->

2025-02-16 18:27 UTC, johlju requested changes
> Reviewed 9 of 10 files at r8, 52 of 52 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532)* status: all files reviewed, 9 unresolved discussions (waiting on @dan-hughes)

___
*[`source/Public/Get-DnsClientServerStaticAddress.ps1` line 16 at r7](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OGOvorl9Cf0xRNpmbCm:-OJEwu_v1XmgYVsAwq5o:b-l57fkx) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/977ecead86841ad30946fcc25c16d2d32aacb499/source/Public/Get-DnsClientServerStaticAddress.ps1#L16)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Valid point, but instead of a prefix maybe a suffix instead? Then searching for usages across repos may be easier as atleast the start of the function name matches.
</blockquote></details>

This is not relevant anymore since we are moving them back to a private module and not a Public function. But I think it is more best practice to add a prefix than a suffix, so they are not mixed up with commands from another module, but I can see your point of the discovery so I'm not sure. :thinking: But that is something we can think about 'till next time :slightly_smiling_face: 
___
*[`source/DSCResources/DSC_DefaultGatewayAddress/DSC_DefaultGatewayAddress.psm1` line 6 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEuocT5YbeIcA12nI8:-OJEuocT5YbeIcA12nI9:bahcpuf) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_DefaultGatewayAddress/DSC_DefaultGatewayAddress.psm1#L6)):*
> ```PowerShell
> Import-Module -Name (Join-Path -Path $modulePath `
>         -ChildPath (Join-Path -Path 'NetworkingDsc.Common' `
>             -ChildPath 'NetworkingDsc.Common.psm1'))
> ```

DO we need to specify the psm1 file, isn't it enough with the folde `NetworkingDsc.Common`? If so, throughout.



_Code quote:_
```PowerShell
-ChildPath 'NetworkingDsc.Common.psm1'
```
___
*[`source/DSCResources/DSC_NetAdapterLso/DSC_NetAdapterLso.psm1` line 7 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEvZql9eU61VuRXjGc:-OJEvZql9eU61VuRXjGd:b-ghqni8) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_NetAdapterLso/DSC_NetAdapterLso.psm1#L7)):*
> ```PowerShell
>         -ChildPath (Join-Path -Path 'NetworkingDsc.Common' `
>             -ChildPath 'NetworkingDsc.Common.psm1'))
>             
> ```

Blank spaces here too. Okay.. there are in most files it seems. So thoughtout. :slightly_smiling_face: 



_Code quote:_
```PowerShell
···········
```
___
*[`source/DSCResources/DSC_DnsConnectionSuffix/DSC_DnsConnectionSuffix.psm1` line 7 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEvBXP9p_cxLnmzXcf:-OJEvBXP9p_cxLnmzXcg:b3ogd9h) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_DnsConnectionSuffix/DSC_DnsConnectionSuffix.psm1#L7)):*
> ```PowerShell
>         -ChildPath (Join-Path -Path 'NetworkingDsc.Common' `
>             -ChildPath 'NetworkingDsc.Common.psm1'))
>             
> ```

Here are those blank spaces again :thinking: Strange.



_Code quote:_
```PowerShell
···········
```
___
*[`source/DSCResources/DSC_HostsFile/DSC_HostsFile.psm1` line 7 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEvN1L7AryZiEovqo5:-OJEvN1L7AryZiEovqo6:bj59qmg) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_HostsFile/DSC_HostsFile.psm1#L7)):*
> ```PowerShell
>         -ChildPath (Join-Path -Path 'NetworkingDsc.Common' `
>             -ChildPath 'NetworkingDsc.Common.psm1'))
>             
> ```

Blank spaces here too.



_Code quote:_
```PowerShell
···········
```
___
*[`source/DSCResources/DSC_NetAdapterBinding/DSC_NetAdapterBinding.psm1` line 7 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEvYP90EVsEPHLAopM:-OJEvYP90EVsEPHLAopN:bj59qmg) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_NetAdapterBinding/DSC_NetAdapterBinding.psm1#L7)):*
> ```PowerShell
>         -ChildPath (Join-Path -Path 'NetworkingDsc.Common' `
>             -ChildPath 'NetworkingDsc.Common.psm1'))
>             
> ```

Blank spaces here too.



_Code quote:_
```PowerShell
···········
```
___
*[`tests/Unit/NetworkingDsc.Common/Public/Convert-CIDRToSubnetMask.Tests.ps1` line 37 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJF-18TE2nC-KIXeXIy:-OJF-18TE2nC-KIXeXIz:b69bhae) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/tests/Unit/NetworkingDsc.Common/Public/Convert-CIDRToSubnetMask.Tests.ps1#L37)):*
> ```PowerShell
>     Import-Module -Name $script:subModulePath -Force -ErrorAction 'Stop'
> 
>     $PSDefaultParameterValues['InModuleScope:ModuleName'] = $script:subModuleName
> ```

I was hoping we could import the main module which will import the private module into the module scope and the `InModuleScope` would see the commands in the private module. But since you made it import here separately it didn't work like I was expecting? 



_Code quote:_
```PowerShell
$PSDefaultParameterValues['InModuleScope:ModuleName'] = $script:subModuleName
```
___
*[`tests/Integration/DSC_Firewall.Integration.Tests.ps1` line 47 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEyuje99BeVpgm9-9M:-OJEyujf91qAg2W7wMVt:b-mel3yr) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/tests/Integration/DSC_Firewall.Integration.Tests.ps1#L47)):*
> ```PowerShell
>     Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath '..\TestHelpers\CommonTestHelper.psm1')
> 
>     $script:subModuleName = 'NetworkingDsc.Common'
> ```

Why are we importing the private module in an integration test?



_Code quote:_
```PowerShell
$script:subModuleName = 'NetworkingDsc.Common'
```
___
*[`tests/Integration/DSC_Firewall.Integration.Tests.ps1` line 49 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEyRa_6UBYFJ_ZsdmP:-OJEyRaa9llN9988GOzO:b-9yi68v) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/tests/Integration/DSC_Firewall.Integration.Tests.ps1#L49)):*
> ```PowerShell
>     $script:subModuleName = 'NetworkingDsc.Common'
> 
>     $script:parentModule = Get-Module -Name $script:dscModuleName -ListAvailable | Select-Object -First 1
> ```

Why do we need to select the first here, why are they more than one module installed when this runs? :thinking: 



_Code quote:_
```PowerShell
| Select-Object -First 1
```
___
*[`source/DSCResources/DSC_NetAdapterAdvancedProperty/DSC_NetAdapterAdvancedProperty.psm1` line 7 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEvSwo-TrrGZCNyJTb:-OJEvSwo-TrrGZCNyJTc:bj59qmg) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_NetAdapterAdvancedProperty/DSC_NetAdapterAdvancedProperty.psm1#L7)):*
> ```PowerShell
>         -ChildPath (Join-Path -Path 'NetworkingDsc.Common' `
>             -ChildPath 'NetworkingDsc.Common.psm1'))
>             
> ```

Blank spaces here too.



_Code quote:_
```PowerShell
···········
```


<!-- Sent from Reviewable.io -->

2025-02-16 19:08 UTC, dan-hughes reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532)* status: 80 of 108 files reviewed, 9 unresolved discussions (waiting on @johlju)

___
*[`source/DSCResources/DSC_DefaultGatewayAddress/DSC_DefaultGatewayAddress.psm1` line 6 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEuocT5YbeIcA12nI8:-OJF8KsD3wfmpIu373PC:b-896fix) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_DefaultGatewayAddress/DSC_DefaultGatewayAddress.psm1#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

DO we need to specify the psm1 file, isn't it enough with the folde `NetworkingDsc.Common`? If so, throughout.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DnsConnectionSuffix/DSC_DnsConnectionSuffix.psm1` line 7 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEvBXP9p_cxLnmzXcf:-OJF8Lt-4a8iQC8ffi3X:b-896fix) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_DnsConnectionSuffix/DSC_DnsConnectionSuffix.psm1#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Here are those blank spaces again :thinking: Strange.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_HostsFile/DSC_HostsFile.psm1` line 7 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEvN1L7AryZiEovqo5:-OJF8QBBAsArAfUS2GXn:b-896fix) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_HostsFile/DSC_HostsFile.psm1#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Blank spaces here too.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_NetAdapterAdvancedProperty/DSC_NetAdapterAdvancedProperty.psm1` line 7 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEvSwo-TrrGZCNyJTb:-OJF8S5hDBJj2ZPJxNmh:b-896fix) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_NetAdapterAdvancedProperty/DSC_NetAdapterAdvancedProperty.psm1#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Blank spaces here too.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_NetAdapterBinding/DSC_NetAdapterBinding.psm1` line 7 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEvYP90EVsEPHLAopM:-OJF8SxK6k2G1X5cnOWQ:b-896fix) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_NetAdapterBinding/DSC_NetAdapterBinding.psm1#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Blank spaces here too.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_NetAdapterLso/DSC_NetAdapterLso.psm1` line 7 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEvZql9eU61VuRXjGc:-OJF8TrkEAxeU050ZL84:b-896fix) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/source/DSCResources/DSC_NetAdapterLso/DSC_NetAdapterLso.psm1#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Blank spaces here too. Okay.. there are in most files it seems. So thoughtout. :slightly_smiling_face:
</blockquote></details>

Done.
___
*[`tests/Integration/DSC_Firewall.Integration.Tests.ps1` line 47 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEyuje99BeVpgm9-9M:-OJF8y3_DvrqF1wXK27M:bmr95mx) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/tests/Integration/DSC_Firewall.Integration.Tests.ps1#L47)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Why are we importing the private module in an integration test?
</blockquote></details>

Using one of the functions from within the module. This happened in the Pester 4 tests. 
___
*[`tests/Integration/DSC_Firewall.Integration.Tests.ps1` line 49 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJEyRa_6UBYFJ_ZsdmP:-OJF8wmhE2z8fpuyB07y:b-896fix) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/tests/Integration/DSC_Firewall.Integration.Tests.ps1#L49)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Why do we need to select the first here, why are they more than one module installed when this runs? :thinking:
</blockquote></details>

Done.
___
*[`tests/Unit/NetworkingDsc.Common/Public/Convert-CIDRToSubnetMask.Tests.ps1` line 37 at r9](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-OJF-18TE2nC-KIXeXIy:-OJF8fqx-NBHuMJSFArr:b-fbk14j) ([raw file](https://github.com/dsccommunity/NetworkingDsc/blob/b6f44aabd31ad46b631c8ec5ae40539ccb41c0c9/tests/Unit/NetworkingDsc.Common/Public/Convert-CIDRToSubnetMask.Tests.ps1#L37)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I was hoping we could import the main module which will import the private module into the module scope and the `InModuleScope` would see the commands in the private module. But since you made it import here separately it didn't work like I was expecting?
</blockquote></details>

It did not work like that. Not sure why though. What you say makes sense but if I change it back Pester does not seem to find the functions.


<!-- Sent from Reviewable.io -->

2025-03-16 08:40 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 28 of 28 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/NetworkingDsc/532#-:-OLT69DA6LPs4ge1aNbQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)



<!-- Sent from Reviewable.io -->

2025-03-16 08:40 UTC, merged